spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}7c41aaccdea8e3d7bbe4acb6e6f5d3bfa168faec0d999579e0d1b5cc7ddd07a3'

token:
  expiration_time: 864000000  # 1 day
  secret: '{cipher}f009a0617696bd903d2fe20e368adf8098faf313fad5106ce9d45982ff3e28a58cc53ff31156665d1ba605a20235a8ccbc160cfcb0325fb6a07a2eb2b52e1e21'

gateway:
  ip: 192.168.0.33

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User's orders is empty